apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-soknad:{{version}}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /
    initialDelay: 5
  readiness:
    path: /
    initialDelay: 5
  prometheus:
    enabled: false
    path: /metrics
  istio:
    enabled: true
  ingresses:
    - https://familie-ef-soknad.nais.aura-q.no
  vault:
    enabled: true
  webproxy: true
  env:
    - name: APP_VERSION
      value: "{{version}}"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
