version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

executors:
  nais-deployer:
    environment:
      TEAM: teamfamilie
    docker:
      - image: navikt/deployment-cli:latest

jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - run:
          name: Add github to known hosts
          command: |
            mkdir ~/.ssh
            echo "github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - 'd4:c2:10:f7:91:30:c2:f0:55:93:8b:8f:b5:cd:6c:49'
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate version number, github token and docker image tags
          command: |
            export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"
            echo "export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"" >> /home/circleci/project/properties.env
            echo "export DOCKER_TAG=\"$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> /home/circleci/project/properties.env
            cat properties.env >> $BASH_ENV
            echo $BASH_ENV
      - run:
          name: Installer npm pakker
          command: |
            npm ci
      - run:
          name: Bygg React app
          command: |
            npm run build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  deploy_docker:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Sett opp environment for docker
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Slett test resources
          command: rm -rf development
      - run:
          name: Bygger Docker image
          command: |
            echo $DOCKER_TAG $VERSION
            docker build -t $DOCKER_TAG .
      - run:
          name: Docker push
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            echo "Pushing with tag $DOCKER_TAG"
            docker push $DOCKER_TAG
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - properties.env

  deploy_dev:
    executor: nais-deployer
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - run:
          name: Set up environment variables
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Create github deployment for stable test
          command: |
            deployment-cli deploy create \
            --cluster=dev-sbs \
            --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
            --appid=${GITHUB_APP_ID} \
            --key-base64=${GITHUB_PRIVATE_KEY} \
            --team=${TEAM} \
            --version=${VERSION} \
            --resource=./nais-dev.yaml

  deploy_prod:
    executor: nais-deployer
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - run:
          name: Set up environment variables
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Create github deployment for stable test
          command: |
            deployment-cli deploy create \
            --cluster=prod-sbs \
            --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
            --appid=${GITHUB_APP_ID} \
            --key-base64=${GITHUB_PRIVATE_KEY} \
            --team=${TEAM} \
            --version=${VERSION} \
            --resource=./nais-prod.yaml

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - deploy_docker:
          context: NAIS deployment
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - deploy_dev:
          context: familie-ci
          requires:
            - deploy_docker
          filters:
            branches:
              only: /.*/
      - deploy_prod:
          context: familie-ci
          requires:
            - deploy_docker
          filters:
            branches:
              only: /.*/
